version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
     - aws s3 sync --delete public s3://movies-db-frontend-bucket1 --cache-control max-age=3600