version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
     - aws s3 sync --delete . "s3://movies-db-frontend-bucket1.s3-website.us-east-2.amazonaws.com"